# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 790cb07118296928c71a7038528d4b59cd38ea113e80e1a062cc713c10ac784b9771e0ca40dee4f9bf2a9cc42a45257d5cf2fc3579dc1e62183e5a686342c339

test:
  secret_key_base: 72b655fb9d8b26fbc53a073ace37843c334d0cb2b538cce085fabd9804642ade830a1fddea99d644230a9e29b3f8b178f2ca48c47beff56e2d5b221b921bf21c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
